name: cyclic_tab_bar
description: A Flutter package for cyclic tab bar component with infinite scrolling and full accessibility support.
version: 1.0.2+1
repository: https://github.com/devaryakjha/cyclic_tab_bar

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.7"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
